[build]
  command = "npm run build:deploy"
  publish = "dist/dentacare-angular/browser"

[build.environment]
  NODE_VERSION = "20"
  DENTACARE_API_BASE_URL = "https://dentacare-api-c8mz.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
